
-- hospital_detailṣ

CREATE TABLE hospital_details(hospital_id serial PRIMARY KEY, name varchar(100) NOT NULL,email varchar(50) UNIQUE NOT NULL,password varchar(30) NOT NULL,contact_no varchar(10) NOT NULL,category varchar(10) NOT NULL, address varchar(150) NOT NULL, latitude real NOT NULL, longitude real NOT NULL, services text[] NOT NULL,timings varchar(15) NOT NULL,website varchar(80) NOT NULL,ratings real NOT NULL,created_on timestamp NOT NULL, isActive smallint NOT NULL DEFAULT 0, last_login timestamp);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Kohinoor Hospital','kohinoor.hospital@gmail.com','kohinoor', '2267556755', 'Private','Kirol Road, Ali Yavar Jung, Kurla (W), Off LBS Road, Mumbai- 400070, Maharashtra ',19.0767937,72.8847191,'{Burn care unit,Cardiology,Neurology,Maternity ward,Orthopaedics}','24*7','www.kohinoorhospitals.in', 3.8, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Bakul Parekh Children Hospital','bakul.hospital@gmail.com','bakul', '2221026858', 'Private','Jayant Arcade, 4th Floor, Rajawadi, M.G.Road, Ghatkopar(E), Mumbai, Maharashtra ',19.0792,72.9037,'{}','24*7','www.bpch.in', 3.3, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Dr Trivedis Maternity and Nursing Home','trivedis.hospital@gmail.com','trivedis', '2261480707', 'Private','1, 2, 3, Gautam Building, Opposite Balaji Temple, Tilak Road, Ghatkopar (E), Mumbai, Maharashtra',19.0783,72.9057,'{}','24*7','www.nilesaakarivf.in', 2.3, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('H. J. Doshi Ghatkopar Hindu Sabha Hospital','doshi.hospital@gmail.com','doshi', '2225094451', 'Private','Shradhanand Road, Ghatkopar (W), Mumbai, Maharashtra',19.0853,72.9062,'{Cardiology,Neurology,Maternity ward}','24*7','www.hjdoshi.com', 3.9, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Dr .Desais Nursing Home','desais.hospital@gmail.com','desais', '2226525251', 'Private','S.G.Barve Road, Kurla, Mumbai-400070, Maharashtra',19.0625228,72.8829242,'{Maternity ward}','24*7','drdesaidesaimaternitynursinghome.justdial.com', 4.2, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Ashvini Maternity and Surgical Nursing Home','ashvini.hospital@gmail.com','ashvini', '2225140472', 'Private','121, Nehru Nagar, Kurla (E), Mumbai, Maharashtra',19.0769,72.843,'{Maternity ward}','24*7','www.ashwinimaternity.com', 4.3, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Shreeji Hospital','shreeji.hospital@gmail.com','shreeji', '2225153465', 'Private','Kirol Road, Opp LBS Road, Kurla(W), Mumbai, Maharashtra',19.0844,72.9047,'{Neurology,Maternity ward}','24*7','www.shreejihospital.in', 4.5, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Varun Cardiac Clinic','varun.hospital@gmail.com','varun', '2225010600', 'Private','Nilkanth Shopping Centre Corner, Cama Lane, Ghatkopar (W), Mumbai, Maharashtra',19.0825,72.9049,'{Cardiology}','24*7','varuncardiacclinic.justdial.com', 4.4, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Aryan Hospital and Iccu - Kurla-Mumbai','aryan.hospital@gmail.com','aryan', '2225275999', 'Private','101-102, Gayatridham, Derasar Lane, Ghatkopar (E), Mumbai, Maharashtra ',19.082354,72.9051026,'{Cardiology,Orthopaedics}','24*7','www.medscapeindia.com', 4, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('CGHS Dispensary No.6, Ghatkopar','cghs.hospital@gmail.com','cghs', '2225149229', 'Private','Sagar Palace B Wing, Sonapur Lane, F.P.P. Marg, Off L B S Marg, Kurla (W), Mumbai, Maharashtra',19.0754649,72.8770505,'{}','24*7','www.cghs.nic.in', 3.7, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Nayan Eye Centre','nayan.hospital@gmail.com','nayan', '9820998830', 'Private','Samaj Bhavan, 5th Floor, Joshi Lane, M G Road, Ghatkopar, Mumbai, Maharashtra',19.0825,72.9067,'{ophthalmology}','10-13,17-20','nayaneyecentre.in', 4.7, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Dr Mehta Nursing Home','mehta.hospital@gmail.com','mehta', '2225062742', 'Private','Chandrika Bldg., Ground Floor, R.B.Mehta Rd, Ghatkopar (E), Mumbai, Maharashtra',19.0748,72.9066,'{}','10-20','drmehtanursinghome.justdial.com', 1, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Ashirwad Heart Hospital','ashirvad.hospital@gmail.com','ashirvad', '2221025911', 'Private','198/1, Garodia Palace, Garodia Nagar, 90 Feet Road, Ghatkopar (E), Mumbai, Maharashtra',19.0762,72.9055,'{Cardiology}','24*7','ashirwadhearthospital.com', 3.1, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Rane Heart Hospital','rane.hospital@gmail.com','rane', '2225258404', 'Private','1, Vivek - 67, Tilak Road, Ghatkopar (E), Mumbai, Maharashtra',19.0695,72.9038,'{Cardiology}','24*7','www.raneheartcare.com ', 3.7, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('City Hospital And Reserch Centre','city.hospital@gmail.com','city', '2225041888', 'Private','37, Pestom Sagar, Road No.2, Chembur, Mumbai, Maharashtra',19.0811,72.8819,'{Cardiology,Neurology,Maternity ward,Orthopaedics}','24*7','city-hospital.com', 3.3, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Kolekar Hospital','kolekar.hospital@gmail.com','kolekar', '2222520115', 'Private','Sagar Palace B Wing, Sonapur Lane, F.P.P. Marg, Off L B S Marg, Kurla (W), Mumbai, Maharashtra',19.0598,72.9011,'{Maternity ward,Orthopaedics}','24*7','kolekarhospital.justdial.com', 4.3, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Aayush Eye Clinic','aayush.hospital@gmail.com','aayush', '2225288306', 'Private','Plot No. 955, 201, Coral Classic, 956, 20th Rd, Chembur Gaothan, Chembur (E), Mumbai-400071, Maharashtra ',19.0597,72.899,'{Orthopaedics}','10-13,17-20','aayusheye.com', 4.5, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Aadhar Orthodic Hospital','aadhar.hospital@gmail.com','aadhar', '2221023211', 'Private','103, Tilak Rd, Maheshwar Nagar, Sindhu Wadi, Ghatkopar (E), Mumbai-400077, Maharashtra ',19.0784,72.9058,'{Orthopaedics}','24*7','aadharorthopaedichospital.justdial.com', 4.7, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Nidan Hospital','nidan.hospital@gmail.com','nidan', '2225165130', 'Private','22, 2nd Floor Laxmi Shopping Centre, Ghatkopar(W), Mumbai-400086, Maharashtra ',19.0866,72.9083,'{}','8-20','nidandiagnosticcentre.com', 3.1, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Sharan Hospital','sharan.hospital@gmail.com','sharan', '8071280749', 'Public','Dipti Solitaire, 101, MG Road, Above Axis Bank, Kapol wadi, Pant Nagar, Ghatkopar (W), Mumbai-400086, Maharashtra ',19.0879,72.9061,'{Orthopaedics,ophthalmology}','9-21','drshaivalchauhansharanhospital.justdial.com', 5, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Dr. Vinod Joshi Maternity Nursing Home','vinodjoshi.hospital@gmail.com','vinodjoshi', '2225133323', 'Private','Ground floor, Devika Niwas, next to MG Road, Kapol wadi, Ghatkopar(W), Mumbai- 400086, Maharashtra',19.0868,72.906,'{Maternity ward}','24*7','drvinodjoshimaternitynursinghome.justdial.com', 4, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Aesthetica  Clinic','aesthetica.hospital@gmail.com','aesthetica', '7303344369', 'Private','Shop No.12, Building 19 B, Kohinoor City, Phase -2, Near Kohinoor Hospital, Premier Residencies, Kurla(W), Mumbai-400070, Maharashtra',19.0778,72.8857,'{Maternity ward}','10-21','www.aestheticaclinic.com', 4, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Tara Neo-Surg. Hospital','tara.hospital@gmail.com','tara', '2221021603', 'Private','C-5, Satyam Shopping Centre, Mahatma Gandhi Road, Ghatkopar (E), Mumbai 400077, Maharashtra',19.0757,72.903,'{}','9-24','www.pedsurgeon.com', 5, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Nivaran Dental Diagnostic Centre','nivaran.hospital@gmail.com','nivaran', '7208001050', 'Private','106, Charisma Centre, 1st Floor, Opp Vagads, Above Cambridge Showroom, Chembur (E), Mumbai 400071, , Maharashtra',19.0601,72.903,'{}','8-21','nivarandentaldiagnosticcentrechembur.justdial.com', 4, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Varsha Hospital','varsha.hospital@gmail.com','varsha', '2256133327', 'Private','Patelwadi Kurla, Vidyavihar Society, Kurla, Mumbai 400070, Maharashtra',19.0832,72.8991,'{}','10-21','varshahospitalmumbai.justdial.com', 4.3, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Pancholi Hospital','pancholi.hospital@gmail.com','pancholi', '2225066108', 'Private','90 Feet Road, Sudarshan Society, Garodia Nagar, Ghatkopar (E), Mumbai-400071, Maharashtra ',19.0743,72.9057,'{Maternity ward,Orthopaedics}','24*7','pancholihospitalmumbai.justdial.com', 3.5, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Habib Hospital','habib.hospital@gmail.com','habib', '2225031000', 'Private','Plot No. 345, 345/1 & 238, AH Wadia Marg, Old Agra Road, Opp. Shalimar Hotel, Off L. B. S. Road, Kurla (W), Mumbai-400070, Maharashtra',19.0783,72.88,'{Orthopaedics,ophthalmology}','24*7','habibhospital.com', 3.5, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Joy Hospital','joy.hospital@gmail.com','joy', '2225223939', 'Private','Door No. 423 AB, 10th Road, Opposite Post Office, Jai Ambe Nagar, Chembur Gaothan, Chembur (E), Mumbai-400071, Maharashtra',19.0559,72.8974,'{Orthopaedics}','24*7','www.lapsurgeon.in', 3.2, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Sushrut Hospital','sushrut.hospital@gmail.com','sushrut', '2225265555', 'Private','365, Swastik Park, Chembur (E), Mumbai-400071, Maharashtra',19.0565,72.8895,'{Cardiology}','24*7','sushruthospital.org', 4.5, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Bhaba Hospital','bhaba.hospital@gmail.com','bhaba', '2222642541', 'Private','Waterfield Road, Bandra (W), Mumbai-400050, Maharashtra',19.0575,72.8336,'{Orthopaedics,ophthalmology}','24*7','bhabhahospitalmumbai.justdial.com', 3.6, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Aaradhyaji Medical Center','aaradhyaji.hospital@gmail.com','aaradhyaji', '8291851581', 'Private','93, Baristar Nath Road, Garodia Nagar, Ghatkopar (E), Mumbai-400077, Maharashtra ',19.0757,72.9104,'{}','7-20','aaradhyaji-lions-ghatkopar-medical-centre.business.site', 3.9, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Rajawadi Hospital','rajawadi.hospital@gmail.com','rajawadi', '2221025610', 'Public','7, M G Road, Near Somaiya College, Ghatkopar East, Rajawadi Colony, Ghatkopar (E), Mumbai-400077, Maharashtra',19.0787,72.9012,'{Maternity ward,Orthopaedics}','24*7','rajawadihospitalmumbai.justdial.com', 3.8, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Mumbai Heart Clinic','mumbaiheart.hospital@gmail.com','mumbaiheart', '2225258404', 'Private','37, Pestom Sagar Rd Number 2, Pestom Sagar Colony, Chembur (E), Mumbai-400089, Maharashtra',19.0695,72.9038,'{Cardiology}','24*7','www.asianheartinstitute.org', 4.6, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Sarvodaya Hospital','sarvodaya.hospital@gmail.com','sarvodaya', '2225162253', 'Private','Gandhi Nagar, Kirti Vihar, Ghatkopar (W), Mumbai-400086, Maharashtra',19.089666,72.9073832,'{Maternity ward,Orthopaedics,ophthalmology}','9-16','www.sarvodayahospital.com', 3.7, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Disha Hospital','disha.hospital@gmail.com','disha', '9004179994', 'Private','Om Sri Sai Dham CHS, Andheri - Ghatkopar Road Asalpha, Jambhulpada, Prem Nagar, Azad Nagar, Ghatkopar (W), Mumbai-400084, Maharashtra',19.087175,72.8900049,'{Maternity ward,Orthopaedics}','24*7','www.dishaeye.org', 3.4, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('K.J. Somaiya Hospital','kjsomaiya.hospital@gmail.com','kjsomaiya', '2224090253', 'Private','Somaiya Ayurvihar Complex, Eastern Express Highway, Sion (E), Mumbai-400022, Maharashtra',19.0521328,72.8709186,'{Cardiology,Neurology,Maternity ward,Orthopaedics,ophthalmology}','24*7','https://www.somaiya-ayurvihar.org', 3.5, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Bombay Hospital & Medical Research Centre','bombay.hospital@gmail.com','bombay', '2222067676', 'Private','Sion (W), Chuna Bhatti, Mumbai-400022, Maharashtra',19.053734,72.8719839,'{Cardiology,Neurology}','24*7','bombayhospital.com', 3.8, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Apollo Spectra Hospital','appolo.hospital@gmail.com','appolo', '2243344600', 'Public','Ujagar Compound, Opp. Deonar Bus Depot Main Gate, MBPT Colony, Deonar, Chembur (E), Mumbai-400088, Maharashtra ',19.0481734,72.8837379,'{Maternity ward,Orthopaedics}','24*7','www.apollospectra.com', 4.7, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Inlaks General Hospital','inlaks.hospital@gmail.com','inlaks', '2261500300', 'Private','Inlaks Hospital Road, Chembur Colony, Indira Nagar, Chembur (E), Mumbai- 400074, Maharashtra',19.0461,72.8944,'{Cardiology,Neurology,Maternity ward,Orthopaedics,ophthalmology}','24*7','www.inlakshospital.com', 2.9, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Zen Multi Speciality Hospital','zen.hospital@gmail.com','zen', '2225260066', 'Public','Plot No 425, 10th Road Near Sandu Garden, Jai Ambe Nagar, Chembur Gaothan, Chembur (E), Mumbai-400071, Maharashtra ',19.056,72.8968,'{Neurology,Maternity ward,Orthopaedics}','24*7','www.zenhospital.in', 4.2,NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Surana Sethia Hospital','surana.hospital@gmail.com','surana', '2233783378', 'Private','Sion - Trombay Rd, Suman Nagar, Chembur (E), Mumbai-400071, Maharashtra',19.0536,72.887,'{Orthopaedics,ophthalmology}','24*7','suranahospital.in', 4.3,NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Christian Village Municipal Hospital','christian.hospital@gmail.com','christian', '2267309709', 'Public','House No 225/c, Kurla West,, House No 225/c, Hallow Pull Rd, Christian Gaon, Kurla (E), Mumbai-400070, Maharashtra',19.0815,72.8831,'{}','24*7','christianvillagedispensary.justdial.com', 5, NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Masoom Child Hospital','masoom.hospital@gmail.com','masoom', '2225040692', 'Private','Next To Subiksha, W, New Dwarkapuri Building, LBS Rd, Christian Gaon, Kurla, Mumbai-400070, Maharashtra',19.0818,72.882,'{}','24*7','masoomchildrenhospital.justdial.com', 4.4,NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Agashe Hospital','agashe.hospital@gmail.com','agashe', '2242435000', 'Private','Next to Fauzia hospital and Ashok Leyland Showroom, Vrindavan, LBS Rd, Kurla (W), Kurla, Mumbai-400070, Maharashtra',19.0807355,72.8801377,'{Orthopaedics}','24*7','www.punesurgeon.com', 4.7,NOW(), 1);
INSERT INTO hospital_details(name,email,password,contact_no,category, address,latitude,longitude,services,timings,website, ratings,created_on, isActive) values('Care Hospital','care.hospital@gmail.com','care', '2225034949', 'Private','Shop No-1,2 & 3, Aero View, Beside Sahara Hotel, Kanta, Kurla (W), Mumbai-400070, Maharashtra',19.0795856,72.8801073,'{Orthopaedics}','24*7','www.carehospitals.com', 3.2, NOW(), 1);
SELECT * from hospital_details;

-- user_details

CREATE TABLE user_details(user_id serial PRIMARY KEY, name varchar(20) NOT NULL,email varchar(30) UNIQUE NOT NULL,password varchar(30) NOT NULL,contact_no varchar(10) NOT NULL,emergency_contact_no varchar(10) NOT NULL, blood_group varchar(5) NOT NULL,dob date NOT NULL,gender varchar(10) NOT NULL,height smallint, weight smallint,allergies varchar(50), address varchar(50) NOT NULL, pincode varchar(6) NOT NULL,created_on timestamp NOT NULL,last_login timestamp);
INSERT INTO user_details(name,email,password,contact_no,emergency_contact_no, blood_group,dob,gender,height,weight,allergies, address,pincode,created_on) values('Atashi','atashi.khatua@gmail.com','star','8976590206', '9819710770','B+','1997-02-27','Female',6,60, 'dust','284,juhu tara road,Santacruz','400049', NOW());
SELECT * from user_details;

-- service_feedback

CREATE TABLE service_feedback(service_feedback_id serial PRIMARY KEY, user_id INT NOT NULL,initiative varchar(5) NOT NULL,ratings smallint NOT NULL,liking varchar(50),suggestions varchar(50),recommend varchar(5) NOT NULL,submitted_on timestamp NOT NULL);
INSERT INTO service_feedback(user_id, initiative, ratings, liking, suggestions, recommend, submitted_on) values(1,'Yes',4,'Open/closed status of hospitals and ambulances', 'Tracking of ambulance','Yes', NOW());
SELECT * from service_feedback;

-- hospital_feedback

CREATE TABLE hospital_feedback(hospital_feedback_id serial PRIMARY KEY, user_id INT NOT NULL,hospital_name varchar(50) NOT NULL, cleanliness_rating smallint NOT NULL,availability_rating smallint NOT NULL,preparedness_rating smallint NOT NULL,overall_rating smallint NOT NULL,recommend varchar(5) NOT NULL,comments varchar(50),submitted_on timestamp NOT NULL);
INSERT INTO hospital_feedback(user_id, hospital_name, cleanliness_rating, availability_rating, preparedness_rating, overall_rating, recommend, comments, submitted_on) values(1,'Kohinoor Hospital', 4, 4, 4, 4 ,'Yes','Bad infrastructure', NOW());
SELECT * from hospital_feedback;

-- user_history

CREATE TABLE user_history(user_history_id serial PRIMARY KEY, user_id INT NOT NULL,hospital_name varchar(50) NOT NULL,visited_on timestamp NOT NULL);
INSERT INTO user_history(user_id, hospital_name,visited_on) values(1,'Kohinoor Hospital', NOW());
SELECT * from user_history;

-- ambulance_details

CREATE TABLE ambulance_details(ambulance_id serial PRIMARY KEY, operator_name varchar(20) NOT NULL,operator_contact_no varchar(10) NOT NULL,vehicle_no varchar(10) UNIQUE NOT NULL,password varchar(30) NOT NULL,type varchar(10) NOT NULL, first_aid_kit varchar(5) NOT NULL, oxygen_mask varchar(5) NOT NULL,created_on timestamp NOT NULL,last_login timestamp);
INSERT INTO ambulance_details(operator_name,operator_contact_no,vehicle_no, password,type,first_aid_kit,oxygen_mask,created_on) values('Ramesh Gupta','7897898965','MH02EC1479', 'hello', 'Normal','Yes','Yes', NOW());
SELECT * from ambulance_details;

-- user_ambulance_tracking

CREATE TABLE user_ambulance_tracking(user_id int, ambulance_id int, userlklat real, userlklong real, ambulancelklat real, ambulancelklong real, status varchar(20), last_updated_on timestamp NOT NULL);
INSERT INTO user_ambulance_tracking(user_id,ambulance_id,userlklat, userlklong,ambulancelklat,ambulancelklong, status, last_updated_on) values(1,1,NULL,NULL,NULL,NULL,'Unavailable', NOW());
SELECT * from user_ambulance_tracking;
